// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OpenMasjid-Solutions
/**
 * What a Raspberry Pi screen is showing, right now, as a picture.
 *
 * The one question a remote admin cannot otherwise answer. Everything else the panel knows is a
 * claim the device made about itself — "I am drawing", "the display is on", "my last frame was a
 * second ago" — and every one of those was true on the day somebody rang to say the television in
 * the main hall was blank. A frame read straight out of `/dev/fb0` is the only evidence that
 * settles it.
 *
 * ## Why these live on disk and not in the store
 *
 * `db.json` is read whole into memory, rewritten whole on every change, and held in every place
 * that touches settings. A 1080p PNG is a few hundred kilobytes; base64 in JSON makes it a third
 * bigger again, and one per screen would put megabytes of image bytes through every single save.
 * So a screenshot is a file, named after the device, and the store keeps only the timestamp — which
 * is what the panel actually renders ("taken 4 seconds ago") and all it needs to decide whether the
 * picture it is about to fetch is the one it asked for.
 *
 * ## One per device, deliberately
 *
 * Not a history. A screenshot answers "what is on the screen now"; nobody has ever wanted the one
 * from last Tuesday, and keeping them would grow without bound on a masjid's disk with no one
 * watching. Each new one replaces the last, and forgetting a screen deletes its file.
 */
import fs from 'node:fs';
import path from 'node:path';
import { config } from './config';

const dir = () => path.join(config.dataDir, 'screenshots');

/**
 * The most a device may upload.
 *
 * A 1920x1080 timetable — flat bands, a photograph behind them — measures 300-800KB as a PNG. Two
 * megabytes is generous for that and still small enough that a device cannot fill a disk by
 * misbehaving, since it can only ever hold ONE file. The route's own body cap is derived from this
 * one rather than chosen separately, because base64 inflates by a third and the two limits
 * disagreeing is exactly how the check-in cap silently discarded every check-in for weeks.
 */
export const SCREENSHOT_MAX_BYTES = 2_000_000;

/** A device id is generated by us and matches this; anything else never reaches the filesystem. */
const safeId = (id: string): string | null => (/^[A-Za-z0-9_-]{1,64}$/.test(id) ? id : null);

const fileFor = (deviceId: string): string | null => {
  const id = safeId(deviceId);
  return id ? path.join(dir(), `${id}.png`) : null;
};

/** True if `buf` starts with the PNG signature. */
export function looksLikePng(buf: Buffer): boolean {
  const sig = [137, 80, 78, 71, 13, 10, 26, 10];
  if (buf.length < sig.length) return false;
  return sig.every((b, i) => buf[i] === b);
}

/**
 * Store a screenshot for a device, replacing any previous one.
 *
 * Written to a temporary name and renamed, so a panel fetching the picture while a device uploads
 * the next one gets one whole image or the other, never half of each. Returns false if the bytes
 * are not a PNG or are too big — the caller answers 400, because a device that got this wrong
 * should be told rather than left believing it succeeded.
 */
export function saveScreenshot(deviceId: string, png: Buffer): boolean {
  const file = fileFor(deviceId);
  if (!file) return false;
  if (png.length === 0 || png.length > SCREENSHOT_MAX_BYTES) return false;
  // Checked because this is the one file in the app whose bytes come from a device and are served
  // back to a browser. Serving it as image/png when it is not one is how a stored-XSS gets in.
  if (!looksLikePng(png)) return false;
  fs.mkdirSync(dir(), { recursive: true });
  const tmp = `${file}.part`;
  fs.writeFileSync(tmp, png);
  fs.renameSync(tmp, file);
  return true;
}

/** The stored screenshot for a device, or null. */
export function readScreenshot(deviceId: string): Buffer | null {
  const file = fileFor(deviceId);
  if (!file) return null;
  try {
    return fs.readFileSync(file);
  } catch {
    return null;
  }
}

/** Delete a device's screenshot. Called when a screen is forgotten. */
export function removeScreenshot(deviceId: string): void {
  const file = fileFor(deviceId);
  if (!file) return;
  try {
    fs.unlinkSync(file);
  } catch {
    /* never there, or already gone */
  }
}
